    # main menu colours
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
            {name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
'''
position = "at"
payload = '''
            {name = 'colour_1', ref_table = G.C.SECONDARY_SET, ref_value = 'Spectral'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
match_indent = true

    # intro colours
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
            {name = 'colour_1', ref_table = G.C, ref_value = 'BLUE'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
position = "at"
payload = ''' 
            {name = 'colour_1', ref_table = G.C.SECONDARY_SET, ref_value = 'Spectral'},
            {name = 'colour_2', ref_table = G.C.SECONDARY_SET, ref_value = 'Spectral'},
'''
match_indent = true